### ISSUE TITLE
The method 'DioHttpHeaders.set' has fewer named arguments than those of overridden method 'HttpHeaders.set'

### ISSUE THREAD

**Issue by Kunsect** [flutterchina/dio#689]
I am tried to use package when it Complie the complier shown.
It's working until i run flutter upgrade.

--- 

Compiler message:
/C:/Users/kunsect/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/dio-2.2.2/lib/src/dio_http_headers.dart:70:8: Error: The method 'DioHttpHeaders.set' has fewer named
arguments than those of overridden method 'HttpHeaders.set'.
  void set(String name, Object value) {
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:703:8: Context: This is the overridden method ('set').
  void set(String name, Object value,
       ^
/C:/Users/kunsect/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/dio-2.2.2/lib/src/dio_http_headers.dart:55:8: Error: The method 'DioHttpHeaders.add' has fewer named
arguments than those of overridden method 'HttpHeaders.add'.
  void add(String name, value) {
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:694:8: Context: This is the overridden method ('add').
  void add(String name, Object value,
       ^

FAILURE: Build failed with an exception.

---

[√] Flutter (Channel master, v1.15.4-pre.174, on Microsoft Windows [Version 10.0.18362.657], locale zh-CN)
    • Flutter version 1.15.4-pre.174 at d:\flutter
    • Framework revision 64c5a434d0 (88 minutes ago), 2020-02-26 11:45:41 -0500
    • Engine revision ecdfc91d16
    • Dart version 2.8.0 (build 2.8.0-dev.10.0 73f6d15665)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at d:\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = d:\android-sdk
    • Java binary at: D:\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at D:\android-studio
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • SM G8750 • c3496a6f • android-arm64 • Android 9 (API 28)

**Comment by Kunsect** [comment]
fixed it.

**Comment by shaomaicheng** [comment]
how do you fixed this?

**Comment by Kunsect** [comment]
@shaomaicheng i create a new project by androidx and override the previous code  : )

**Comment by DavidMGT** [comment]
it does not work..I am already android x!

**Comment by asanos908** [comment]
@DavidMGT 
Hi, I might face the same error.
I leave a comment in case you're still facing it.
What I did is: 

1. remove all the cache files from `~/.pub-cache/hosted/pub.dartlang.org/`
2. re install flutter itself.(remove flutter folder, then download same version copy)
3. run `flutter pub cache repair`
4. then my app works fine again

**Comment by scofield-hello** [comment]
I got the same error.
---------------flutter doctor--------------
C:\WINDOWS\system32>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.18.0-6.0.pre.83, on Microsoft Windows [Version 10.0.18363.778], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.6)
[!] IntelliJ IDEA Ultimate Edition (version 2019.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.44.2)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[!] VS Code, 64-bit edition
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

Scanning for devices is taking a long time...\Error 1 retrieving device properties for ro.product.cpu.abi:
error: closed


[√] Connected device (2 available)

! Doctor found issues in 3 categories.

**Comment by alfianakbar** [comment]
I got the same problem:

Flutter 1.18.0-14.0.pre.19 • channel master • https://github.com/flutter/flutter.git
Framework • revision a849daf283 (6 hours ago) • 2020-05-07 18:59:02 -0700
Engine • revision 3953c3ccd1
Tools • Dart 2.9.0 (build 2.9.0-5.0.dev 4da5b40fb6)

I use Dio ^2.1.5

**Comment by klaszlo8207** [comment]
Same here

The method 'DioHttpHeaders.add' has fewer named arguments than those of overridden method 'HttpHeaders.add'.

Flutter 2.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c5a4b4029c (6 days ago) • 2021-03-04 09:47:48 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0

How to fix?
